---
version: '2'
services:
  app:
    image: matus-u/sz-modbus-web:1.4.8
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:10
